### ISSUE TITLE
adding tiptap extensions

### ISSUE THREAD

**Issue by ohisia** [sveltor/nextlint#37]
Hello!

I wonder how I can add tiptap extensions.
My guess is adding them as a props in SvelteEditor component or somewhere 
`onCreated={createdEditor => { editor = createdEditor }}`

Thank you!

**Comment by lynhan318** [comment]
Hi @ohisia ,
Yes you can add custom tiptap extension via `extensions` props
https://github.com/sveltor/nextlint/blob/main/packages/svelte/src/lib/Editor.svelte#L37
Hope that help!

**Comment by ohisia** [comment]
Awesome! Thanks!
