### ISSUE TITLE
Broken example?

### ISSUE THREAD

**Issue by andoppomny** [sveltor/nextlint#55]
I can't get the example from the setup instructions in the README to work.
It says to do
```
  import {type Editor, EditorTheme, SvelteEditor} from '@nextlint/svelte';
```
but `Editor` doesn't seem to be exported by this library. Its content is
```
export { default as SvelteEditor } from './Editor.svelte';
export { default as EditorTheme } from './EditorTheme.svelte';
```
so no `Editor`.

**Comment by rotimi-best** [comment]
Having similar issue

<img width="1372" alt="image" src="https://github.com/sveltor/nextlint/assets/31730715/ed271a95-4f70-4962-aebf-aac191fd65f1">

**Comment by lynhan318** [comment]
Hi @rotimi-best  @andoppomny , 
Yes the docs is outdate. I'm working on update it.

Thanks for report!

**Comment by lynhan318** [comment]
Hi @andoppomny  @rotimi-best ,
Please try the new version [2.1.0](https://www.npmjs.com/package/@nextlint/svelte)
